MvcBlogProject/MvcBlogProject/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers
{
    public class AboutController : Controller
    {
        AboutManager abm = new AboutManager();
        // GET: About
        public ActionResult Index()
        {
            var abautcontent = abm.GetAll();
            return View(abautcontent);
        }
        public PartialViewResult Footer()
        {

            var aboutcontentlist = abm.GetAll();
            return PartialView(aboutcontentlist);
        }
        public PartialViewResult MeetTheTeam()
        {
            AuthorManager authman = new AuthorManager();
            var authorlist = authman.GetAll();
            return PartialView(authorlist);
        }
        [HttpGet]
        public ActionResult UpdateAbout()
        {
            var adminabout = abm.GetAll();
            return View(adminabout);
        }
        [HttpPost]
        public ActionResult UpdateAbout(About p)
        {
            abm.UpdateAboutBM(p);
            return RedirectToAction("UpdateAbout"); 
        }
        
         
    }
}

MvcBlogProject/MvcBlogProject/Controllers/AuthorController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers
{
    public class AuthorController : Controller
    {
        BlogManager blogmanager = new BlogManager();
        AuthorManager authormanager = new AuthorManager();
        // GET: Author
        public PartialViewResult AuthorAbout(int id)
        {
            var authordetail = blogmanager.GetBlogByID(id);
            return PartialView(authordetail);
        }
        public PartialViewResult AuthorPopularPost(int id)
        {
            var blogauthorid = blogmanager.GetAll().Where(x => x.BlogID == id).Select(y => y.AuthorID).FirstOrDefault();

            var authorblogs = blogmanager.GetBlogByAuthor(blogauthorid);
            return PartialView(authorblogs);
        }
        public ActionResult AuthorList()
        {
            var authorlists = authormanager.GetAll();
            return View(authorlists);
        }

        [HttpGet]
        public ActionResult AddAuthor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAuthor(Author p)
        {
            authormanager.AddAuthorBL(p);
            return RedirectToAction("AuthorList");
        }
        [HttpGet]
        public ActionResult AuthorEdit(int id)
        {
            Author author = authormanager.FindAuthor(id);
            return View(author);
        }
        [HttpPost]
        public ActionResult AuthorEdit(Author p)
        {
            authormanager.EditAuthor(p);
            return RedirectToAction("AuthorList");
        }
    }
}

MvcBlogProject/MvcBlogProject/Controllers/BlogController.cs
using BusinessLayer.Concrete;
using System;
using PagedList;
using PagedList.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntityLayer.Concrate;
using DataAccessLayer.Concrate;

namespace MvcBlogProject.Controllers
{
    public class BlogController : Controller
    {

        // GET: Blog
        BlogManager bm = new BlogManager();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult BlogList(int page = 1)
        {
            var bloglist = bm.GetAll().ToPagedList(page, 6);
            return PartialView(bloglist);
        }
        public PartialViewResult FeaturedPosts()
        {

            //1.Post
            #region
            var postTitle1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.blogImage).FirstOrDefault();
            var postDate1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogDate).FirstOrDefault();


            ViewBag.postTitle1 = postTitle1;
            ViewBag.postImage1 = postImage1;
            ViewBag.postDate1 = postDate1;
            #endregion

            //2.Post
            #region
            var postTitle2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.blogImage).FirstOrDefault();
            var postDate2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.postTitle2 = postTitle2;
            ViewBag.postImage2 = postImage2;
            ViewBag.postDate2 = postDate2;
            #endregion

            //3.Post
            #region
            var postTitle3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.blogImage).FirstOrDefault();
            var postDate3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.postTitle3 = postTitle3;
            ViewBag.postImage3 = postImage3;
            ViewBag.postDate3 = postDate3;
            #endregion

            //4.Post
            #region
            var postTitle4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.blogImage).FirstOrDefault();
            var postDate4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.postTitle4 = postTitle4;
            ViewBag.postImage4 = postImage4;
            ViewBag.postDate4 = postDate4;
            #endregion

            //5.Post
            #region
            var postTitle5 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 5).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage5 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 5).Select(y => y.blogImage).FirstOrDefault();
            var postDate5 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 5).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.postTitle5 = postTitle5;
            ViewBag.postImage5 = postImage5;
            ViewBag.postDate5 = postDate5;
            #endregion
            return PartialView();
        }

        public PartialViewResult OtherFeaturedPosts()
        {
            return PartialView();
        }
        public ActionResult BlogDetails()
        {

            return View();
        }
        public PartialViewResult BlogCover(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);

        }
        public PartialViewResult BlogReadAll(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }
        public ActionResult BlogByCategory(int id)
        {
            var BlogListByCategory = bm.GetBlogByCategory(id);
            var CategoryName = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryName).FirstOrDefault();
            ViewBag.CategoryName = CategoryName;

            var CategoryDescription = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryDescription).FirstOrDefault();
            ViewBag.CategoryDescription = CategoryDescription;
            return View(BlogListByCategory);
        }

        public ActionResult AdminBlogList()
        {
            var bloglist = bm.GetAll();
            return View(bloglist);
        }
        public ActionResult AdminBlogList2()
        {
            var bloglist = bm.GetAll();
            return View(bloglist);
        }
        public ActionResult AddNewBlog()
        {
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.values = values;
            Context a = new Context();
            List<SelectListItem> valuesa = (from x in c.Authors.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.AuthorName,
                                                Value = x.AuthorID.ToString()
                                            }).ToList();
            ViewBag.valuesa = valuesa;
            return View();
        }

        [HttpPost]
        public ActionResult AddNewBlog(Blog b)
        {
            bm.BlogAddBL(b);
            return RedirectToAction("AdminBlogList");
        }

        public ActionResult DeleteBlog(int id)
        {
            bm.DeleteBlog(id);
            return RedirectToAction("BlogList");
        }
        [HttpGet]
        public ActionResult UpdateBlog(int id)
        {
            Blog blog = bm.FindBlog(id);
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.values = values;
            Context a = new Context();
            List<SelectListItem> valuesa = (from x in c.Authors.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.AuthorName,
                                                Value = x.AuthorID.ToString()
                                            }).ToList();
            ViewBag.valuesa = valuesa;

            return View(blog);
        }
        [HttpPost]
        public ActionResult UpdateBlog(Blog p)
        {
            bm.UpdateBlog(p);
            return RedirectToAction("AdminBlogList");
        }
        public ActionResult GetCommentByBlog(int id)
        {
            CommentManager   cm = new CommentManager();
            var commentlist = cm.CommentByBlog(id);
            return View(commentlist);
        }

    }
}

MvcBlogProject/MvcBlogProject/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers
{
    public class CategoryController : Controller
    {

         
        CategoryManager cm = new CategoryManager();
        public ActionResult Index()
        {
            var categoryvalues = cm.GetAll();
            return View(categoryvalues); 
        }
        public PartialViewResult BlogDetailsCategoryList()
        {
            var categoryvalues = cm.GetAll(); 
            return PartialView(categoryvalues);
        }
        public ActionResult AdminCategoryList()
        {
            var categoryvalues = cm.GetAll();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AdminCategoryAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AdminCategoryAdd(Category p)
        {
            cm.AddCategory(p);
            return RedirectToAction("AdminCategoryList");
        }
    }
}

MvcBlogProject/MvcBlogProject/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers
{
    public class CommentController : Controller
    {
        CommentManager cm = new CommentManager();
        // GET: Comment
        public PartialViewResult CommentList(int id)
        {
            var commentlist = cm.CommentByBlog(id);
            return PartialView(commentlist);
        }
        [HttpGet]
        public PartialViewResult LeaveComment(int id)
        {
            ViewBag.id = id;
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult LeaveComment(Comment c)
        {
            cm.CommentAdd(c);
            return PartialView();
        }
        public ActionResult AdminCommentLitst()
        {
            var admincommentlist = cm.CommentList();
            return View(admincommentlist);
        }
    }
}

MvcBlogProject/MvcBlogProject/Controllers/MailSubscribeController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers
{
    public class MailSubscribeController : Controller
    {
        [HttpGet]
        public PartialViewResult AddMail()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult AddMail(SubscribeMail p)
        {
            SubscribeMailManager sm = new SubscribeMailManager();
            sm.BLAdd(p);

            return PartialView();
        }
    }
}

MvcBlogProject/MvcBlogProject/Views/Blog/AddNewBlog.cshtml
@model EntityLayer.Concrate.Blog
@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form class="form-group" method="post">
    @Html.Label("Blog Başlığı")
    @Html.TextBoxFor(x => x.BlogTitle, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.values, new { @class = "form-control" })

    <br />
    @Html.Label("Resim Yolu")
    @Html.TextBoxFor(x => x.blogImage, new { @class = "form-control" })

    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.BlogDate, new { @class = "form-control" , @Value = @DateTime.Now.ToShortDateString() })

    <br />
    @Html.Label("Yazar")
     @Html.DropDownListFor(x => x.AuthorID, (List<SelectListItem>)ViewBag.valuesa, new { @class = "form-control" })

    <br />
    @Html.Label("İçerik")
    @Html.TextAreaFor(x => x.BlogContent, 10, 30, new { @class = "form-control" })
    <br />
    <button class="btn btn-success"> Kaydet</button>

</form>

MvcBlogProject/MvcBlogProject/Views/Blog/AdminBlogList.cshtml
@model IEnumerable<EntityLayer.Concrate.Blog>
@{
    ViewBag.Title = "AdminBlogList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Blog Listesi</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Başlık</th>
        <th>Kategori</th>
        <th>Yazar</th>
        <th>Tarih</th>
        <th style="width:30px">Sil</th>
        <th style="width:30px">Güncelle</th>
        <th style="width:30px">Detaylar</th>
        <th style="width:30px">Yorumlar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BlogID</td>
            <td>@item.BlogTitle</td>
            <td>@item.Category.CategoryName</td>
            <td>@item.Author.AuthorName</td>
            <td>@item.BlogDate.ToShortDateString()</td>
            <td><a class="btn btn-danger " style="color:black" href="/Blog//DeleteBlog/@item.BlogID">Sil</a></td>
            <td><a class="btn btn-success" style="color:black" href="/Blog/UpdateBlog/@item.BlogID">Güncelle</a></td>
            <td><a class="btn btn-primary" style="color:black" href="/Blog/BlogDetails/@item.BlogID">Detaylar</a></td>
            <td><a class="btn btn-secondary" style="color:black" href="/Blog/GetCommentByBlog/@item.BlogID">Yorumlar</a></td>

        </tr>
    }
</table>
<a href="/Blog/AddNewBlog" class="btn btn-primary">Yeni Blog Ekle</a>

MvcBlogProject/MvcBlogProject/Views/Blog/AdminBlogList2.cshtml
@model IEnumerable<EntityLayer.Concrate.Blog>
@{
    ViewBag.Title = "AdminBlogList2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Bloglar</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects table-hover">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            ID
                        </th>
                        <th style="width: 10%">
                            Blog Başlığı
                        </th>
                        <th>
                            Blog İçeriği
                        </th>
                        <th width="8%">
                            Yazarı
                        </th>
                        <th style="width:10%">
                            Blog Bar
                        </th>
                        <th style="width: 8%" class="text-center">
                            Kategori
                        </th>
                        <th style="width: 20%">

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {


                        <tr>
                            <td> @item.BlogID  </td>
                            <td> @item.BlogTitle </td>
                            <td>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 200).LastIndexOf(" ")) ...  </td>
                            <td> 
                                
                                        <img alt="Avatar" class="table-avatar"  src="@item.Author.AuthorImage">
                                        <br />
                                        <small>
                                            @item.Author.AuthorName
                                        </small>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-green" role="progressbar" aria-volumenow="57" aria-volumemin="0" aria-volumemax="100" style="width: 57%">
                                    </div>
                                </div>
                                <small>
                                    57% Complete
                                </small>
                            </td>
                            <td class="project-state">
                                <span class="badge badge-secondary">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Blog/BlogDetails/@item.BlogID">
                                    <i class="fas fa-folder">
                                    </i>
                                    Gorüntüle
                                </a>
                                <a class="btn btn-info btn-sm" href="/Blog/UpdateBlog/@item.BlogID">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-warning btn-sm" href="/Blog/GetCommentByBlog/@item.BlogID">
                                    <i class="fas fa-comment">
                                    </i>
                                    Yorumlar
                                </a>
                                <a class="btn btn-danger btn-sm" href="/Blog//DeleteBlog/@item.BlogID">
                                    <i class="fas fa-trash">
                                    </i>
                                    Sil
                                </a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<a href="/Blog/AddNewBlog" class="btn btn-success fa fa-plus">Yeni Blog Ekle</a>

MvcBlogProject/MvcBlogProject/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<EntityLayer.Concrate.Blog>
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@{string color = "";}

<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image:url(/miniblog/images/blog.jpg);opacity:0.9">
    <div class="container">
        <div class="row same-height  ">
            <div class="col-md-10">
                <h3 style="color:white;padding-bottom:10px">@ViewBag.CategoryName</h3>
                <p style="color:lightgrey;font-size:17px">@ViewBag.CategoryDescription</p>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                if (item.Category.CategoryName == "Teknoloji")
                {
                    color = "post-category text-white bg-primary mb-3";
                }
                if (item.Category.CategoryName == "Tarih")
                {
                    color = "post-category text-white bg-danger mb-3";
                }
                if (item.Category.CategoryName == "Film & Dizi")
                {
                    color = "post-category text-white bg-warning mb-3";
                }
                if (item.Category.CategoryName == "Yazılım")
                {
                    color = "post-category text-white bg-success mb-3";
                }
                if (item.Category.CategoryName == "Kültür&Sanat")
                {
                    color = "post-category text-white bg-dark mb-3";
                }
                if (item.Category.CategoryName == "Seyahat")
                {
                    color = "post-category text-white  bg-secondary";
                }
                if (item.Category.CategoryName == "Spor")
                {
                    color = "post-category text-white  bg-secondary";
                }
                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="/Blog/BlogDetails/@item.BlogID"><img src="@item.blogImage" style="height:250px;width:350px" alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="@color">@item.Category.CategoryName</span>
                            <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1"><a href="#">@item.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp;@item.BlogDate.ToShortDateString()</span>
                            </div>
                            <p>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 200).LastIndexOf(" "))</p>
                            <p><a href="/Blog/BlogDetails/@item.BlogID">Devamını Oku...</a></p>
                        </div>
                    </div>
                </div>}
        </div>
    </div>
</div>
@Html.Action("AddMail", "MailSubscribe") 
@Html.Action("Footer", "About")

MvcBlogProject/MvcBlogProject/Views/Blog/BlogCover.cshtml
@model IEnumerable<EntityLayer.Concrate.Blog>
@foreach (var item in Model)
{


<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@item.blogImage');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>
                    <h1 class="mb-4"><a href="#">@item.BlogTitle</a></h1>
                    <div class="post-meta align-items-center text-center">
                        <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                        <span class="d-inline-block mt-1">@item.Author.AuthorName</span>
                        <span>&nbsp;-&nbsp; @item.BlogDate.ToShortDateString()</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>}

MvcBlogProject/MvcBlogProject/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("BlogCover", "Blog")

<div class="site-wrap">
    <section class="site-section py-lg">
        <div class="container">

            <div class="row blog-entries element-animate">

                <div class="col-md-12 col-lg-8 main-content">
                    @Html.Action("BlogReadAll", "Blog")
                    @Html.Action("CommentList", "Comment")
                </div>
                <div class="col-md-12 col-lg-4 sidebar">
                    @Html.Action("AuthorAbout", "Author")
                    @Html.Action("AuthorPopularPost", "Author")
                    @Html.Action("BlogDetailsCategoryList", "Category")
                </div>
            </div>
    </section>
</div>

@*@Html.Action("OtherFeaturedPosts", "Blog")*@
@Html.Action("AddMail", "MailSubscribe")
@Html.Action("Footer", "About")

MvcBlogProject/MvcBlogProject/Views/Blog/BlogList.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IEnumerable<EntityLayer.Concrate.Blog>
@{string color = "";}
<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <h2><b>Post Listesi</b></h2>
            </div>
        </div>
        <div class="row">


            @foreach (var item in Model)
            {
                if (item.Category.CategoryName == "Teknoloji")
                {
                    color = "post-category text-white bg-primary mb-3";
                }
                if (item.Category.CategoryName == "Tarih")
                {
                    color = "post-category text-white bg-danger mb-3";
                }
                if (item.Category.CategoryName == "Film & Dizi")
                {
                    color = "post-category text-white bg-warning mb-3";
                }
                if (item.Category.CategoryName == "Yazılım")
                {
                    color = "post-category text-white bg-success mb-3";
                }
                if (item.Category.CategoryName == "Kültür&Sanat")
                {
                    color = "post-category text-white bg-dark mb-3";
                }
                if (item.Category.CategoryName == "Seyahat")
                {
                    color = "post-category text-white  bg-secondary";
                }

                <div class="col-lg-4 mb-4   ">
                    <div class="entry2">
                        <a href="/Blog/BlogDetails/@item.BlogID"><img style="min-height:250px; max-height:250px" src="@item.blogImage" alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="@color">@item.Category.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1"><a href="#">@item.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp; @item.BlogDate.ToShortDateString()</span>
                            </div> 
                            <p>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 200).LastIndexOf(" "))  </p>
                            <p><a href="/Blog/BlogDetails/@item.BlogID">Devamını Oku</a></p>
                        </div> 
                    </div> 
                </div>
            }
        </div>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
    </div>
</div>

MvcBlogProject/MvcBlogProject/Views/Blog/BlogReadAll.cshtml
@model IEnumerable<EntityLayer.Concrate.Blog>
@foreach (var item in Model)
{



    <div class="post-content-body">
        <p>@item.BlogContent </p>
        <div class="row mb-5 mt-5">
            <div class="col-md-12 mb-4">
                <img src="@item.blogImage" alt="Image placeholder" class="img-fluid rounded">
            </div> 
        </div>
        
    </div>
}

MvcBlogProject/MvcBlogProject/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@Html.Action("FeaturedPosts", "Blog")
@Html.Action("BlogList", "Blog")
@*@Html.Action("OtherFeaturedPosts", "Blog")*@
@Html.Action("AddMail", "MailSubscribe")
@Html.Action("Footer", "About")

MvcBlogProject/MvcBlogProject/Views/Blog/MailSubscribe.cshtml
<div class="site-section bg-lightx">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-md-5">
                <div class="subscribe-1 ">
                    <h2>Haberdar olmak için abone olun</h2>
                    <p class="mb-5">Birbirinden farklı postlara erişmek için tek yapman gereken</p>
                    <form action="#" class="d-flex">
                        <input type="text" class="form-control" placeholder="E-mail adresinizi giriniz...">
                        <input type="submit" class="btn btn-primary" value="Abone ol">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>